# Generated by Django 5.0.4 on 2024-04-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_quiz_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerdetail',
            name='code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='option',
            name='code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
